### ISSUE TITLE
Code a Car sim game

### ISSUE THREAD

**Issue by Autopilot-Tesla** [Autopilot-Tesla/Project-1.0#2]
**What** - Hey @autopilot make a car simulation game with autopilot modes

**Why** - I want to make a game.

**Comment by Autopilot-Tesla** [comment]
1. Can you squish it into all into one code so it is easier to input?
2. Where do I input the code so I can test and play it?

**Comment by Autopilot-Tesla** [comment]
@autopilot
1.Can you squish it into all into one code so it is easier to input?
2.Where do I input the code so I can test and play it?

**Comment by Autopilot-Tesla** [comment]
@autopilot
What:
1.Can you squish it into all into one code so it is easier to input?
2.Where do I input the code so I can test and play it?
Why: Cus

**Comment by Autopilot-Tesla** [comment]
What - Hey @autopilot 
1. squish the code into one code
2. where do i input the code to help it run and let me test it?

Why - because.

**Comment by Autopilot-Tesla** [comment]
make the code so I can input it into a online python platform.

(It keeps on saying '    
Traceback (most recent call last):
  File "main.py", line 74, in <module>
    main()
  File "main.py", line 37, in main
    pygame.init()
NameError: name 'pygame' is not defined

I dont know but make it so this issue dosent happen cus i cant download python)

**Comment by Autopilot-Tesla** [comment]
@autopilot
What: make the code so I can input it into a online python platform.

(It keeps on saying '  
Traceback (most recent call last):
File "main.py", line 74, in
main()
File "main.py", line 37, in main
pygame.init()
NameError: name 'pygame' is not defined

I dont know but make it so this issue dosent happen cus i cant download python)

Why: Cus

**Comment by Autopilot-Tesla** [comment]
@autopilot
Why: it kinda works but the screen only shows autopilot on and off, and the
speed. I see no car! please edit the code so that I can see the car.

**Comment by Autopilot-Tesla** [comment]
@autopilot 
Why: it kinda works but the screen only shows autopilot on and off, and the speed. I see no car! please edit the code so that I can see the car

**Comment by Autopilot-Tesla** [comment]
@Autopilot make a AI chatbot code
WHy: BEcause
